# Site settings
title: Joel Bugarini
email: joelbugarini@gmail.com
description: "of Code and Love "
baseurl: ""
url: "http://joelbugarini.github.io"
twitter_username: joelbugarini
github_username:  joelbugarini

# Build settings
markdown: kramdown
permalink: pretty
comments: true
plugins:
 - jekyll-seo-tag
